name: Docker Image CI

on:
  push:
    tags: [ v* ]

env:
  REGISTRY: hub.oepkgs.net
  IMAGE_NAME: oerv-ci/guix-kernel-cross-build
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Docker Setup BuildX
      uses: docker/setup-buildx-action@v3

    - name: Verify Docker BuildX Version
      run: docker buildx version

    - name: check channels-lock.scm
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          scm:
            - 'channels-lock.scm'

    - name: guix cache
      #if: steps.filter.outputs.scm == 'true'
      run: |
        sed -i "/# recovery guix source url/i RUN --security=insecure sh -c '/entry-point.sh guix time-machine --substitute-urls='https://bordeaux.guix.gnu.org https://bordeaux-singapore-mirror.cbaines.net https://mirror.sjtu.edu.cn/guix ' -C /channels-lock.scm -- archive -r --export linux-libre --target=riscv64-linux-gnu > /tmp/guix_cache'" Dockerfile
        sed -i "/# recovery guix source url/i RUN --security=insecure sh -c 'cat /tmp/guix_cache | /entry-point.sh guix archive --import'" Dockerfile
        cat Dockerfile

    - name: Create a new builder instance
      run: docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ vars.DOCKERHUB_OEPKGS_OERVCI_USERNAME }}
        password: ${{ secrets.DOCKERHUB_OEPKGS_OERVCI_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        allow: security.insecure
        no-cache: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
